const swaggerJsdoc = require('swagger-jsdoc');
const options = {
    // List of files to be processed.
    apis: ['./routes/user.js', './routes/ticket.js', './routes/organization.js'],
    // You can also set globs for your apis
    // e.g. './routes/*.js'
    // basePath: '/',
    swaggerDefinition: {
        info: {
            description: 'Test API with autogenerated swagger doc',
            swagger: '2.0',
            title: 'Q system APIs',
            version: '1.0.0',
        },
        
        // servers: ["http://localhost:3000"]
    },
};
const specs = swaggerJsdoc(options);
// export default specs;
module.exports = specs;